package cli

import (
	"bytes"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"regexp"
	"strings"

	"github.com/portainer/kubesolo/internal/cli/config"
	"github.com/portainer/kubesolo/internal/cli/detect"
	"github.com/portainer/kubesolo/internal/cli/service"
	"github.com/portainer/kubesolo/internal/cli/ui"
	kubesoloconfig "github.com/portainer/kubesolo/internal/config"
	"github.com/portainer/kubesolo/types"
)

// serviceFlagPattern matches a KubeSolo flag in a service definition. The files
// are machine-generated by kubesoloctl or install.sh, in six different init
// system formats, so the flags are extracted by shape rather than by parsing
// each format.
var serviceFlagPattern = regexp.MustCompile(`--[a-z0-9][a-z0-9-]*(?:=(?:"[^"]*"|'[^']*'|[^\s"']+))?`)

// migrateToConfigFile converts a flag-based service definition into a
// configuration file plus a single --config flag.
//
// It runs during an upgrade, after the new binary is in place, because the
// document is produced by that binary's --print-config: the conversion is
// therefore exactly what the binary itself would have resolved, not a
// reimplementation of it.
//
// Without this an upgraded install keeps its flags forever, and those flags
// silently outrank the configuration file — `kubesoloctl config set` on a
// setting the unit also passes would appear to work and change nothing.
//
// It is a no-op when there is nothing to convert, and never fails the upgrade:
// the flags still work, so a failed migration leaves a working install.
func migrateToConfigFile(p *ui.Printer, cfg *config.Config, info *detect.SystemInfo) {
	servicePath := service.FilePath(info.InitSystem)
	if servicePath == "" {
		return
	}

	// Already migrated by an earlier upgrade, or installed fresh with a file.
	if _, err := os.Stat(types.DefaultConfigFile); err == nil {
		return
	} else if !errors.Is(err, fs.ErrNotExist) {
		p.Warn("could not check for an existing configuration file: " + err.Error())
		return
	}

	definition, err := os.ReadFile(servicePath)
	if err != nil {
		// Nothing to convert: a service KubeSolo did not write, or none at all.
		return
	}

	flags := extractServiceFlags(string(definition))
	if len(flags) == 0 {
		return
	}
	for _, f := range flags {
		if strings.HasPrefix(f, "--config") {
			return // already flag-free in the sense that matters
		}
	}

	p.Step("Converting flags to a configuration file")

	document, err := renderConfigFromFlags(flags)
	if err != nil {
		p.Warn("could not convert the existing flags, leaving them in place: " + err.Error())
		return
	}

	if err := os.MkdirAll("/etc/kubesolo", 0o755); err != nil {
		p.Warn("could not create /etc/kubesolo, leaving the flags in place: " + err.Error())
		return
	}
	if err := os.WriteFile(types.DefaultConfigFile, document, 0o600); err != nil {
		p.Warn("could not write the configuration file, leaving the flags in place: " + err.Error())
		return
	}

	// The previous definition is kept: it is the only record of the flags this
	// install ran with, and the way back if the converted one misbehaves.
	backup := servicePath + ".bak"
	if err := os.WriteFile(backup, definition, 0o644); err != nil {
		p.Warn("could not back up " + servicePath + ": " + err.Error())
	}

	cfg.ConfigFile = types.DefaultConfigFile
	mgr, err := service.New(info, cfg.RunMode, cfg.Name)
	if err != nil {
		p.Warn("could not rewrite the service definition, leaving the flags in place: " + err.Error())
		return
	}
	if err := mgr.Install(cfg, cfg.CmdArgs()); err != nil {
		p.Warn("could not rewrite the service definition, leaving the flags in place: " + err.Error())
		return
	}

	p.OK("Settings moved to a configuration file", types.DefaultConfigFile)
	p.Info("previous service definition kept at " + backup)
}

// extractServiceFlags pulls the KubeSolo flags out of a service definition,
// dropping anything that is not a setting the binary understands.
//
// Service files contain flags belonging to other commands — systemctl,
// start-stop-daemon — so each candidate is checked against the flag set rather
// than assumed.
func extractServiceFlags(definition string) []string {
	known := map[string]bool{"config": true, "full": true}
	for _, d := range kubesoloconfig.Describe() {
		if d.Flag != "" {
			known[d.Flag] = true
		}
	}

	var out []string
	seen := map[string]bool{}

	for _, match := range serviceFlagPattern.FindAllString(definition, -1) {
		name, _, _ := strings.Cut(strings.TrimPrefix(match, "--"), "=")
		if !known[strings.TrimPrefix(name, "no-")] || seen[name] {
			continue
		}
		seen[name] = true

		// Shell quoting from the template is stripped: the flag is handed
		// straight to the binary as one argument, not through a shell.
		out = append(out, unquoteShellValue(match))
	}

	return out
}

func unquoteShellValue(arg string) string {
	name, value, hasValue := strings.Cut(arg, "=")
	if !hasValue {
		return arg
	}
	if len(value) >= 2 {
		if (value[0] == '"' && value[len(value)-1] == '"') || (value[0] == '\'' && value[len(value)-1] == '\'') {
			value = value[1 : len(value)-1]
		}
	}
	return name + "=" + value
}

// renderConfigFromFlags asks the installed binary what these flags resolve to.
func renderConfigFromFlags(flags []string) ([]byte, error) {
	args := append(append([]string{}, flags...), "--print-config")

	cmd := exec.Command(config.DefaultInstallPath, args...) //nolint:gosec // the path is fixed and the flags come from a file we wrote
	var stdout, stderr bytes.Buffer
	cmd.Stdout, cmd.Stderr = &stdout, &stderr

	if err := cmd.Run(); err != nil {
		return nil, fmt.Errorf("%s --print-config: %w: %s", config.DefaultInstallPath, err, strings.TrimSpace(stderr.String()))
	}
	if stdout.Len() == 0 {
		return nil, fmt.Errorf("%s --print-config produced no output", config.DefaultInstallPath)
	}

	return stdout.Bytes(), nil
}
