package containerd

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenerateHostsTOML_PlainMirror(t *testing.T) {
	out := generateHostsTOML("docker.io", "https://mirror.corp")

	if !strings.HasPrefix(out, hostsTomlManagedMarker) {
		t.Errorf("expected managed marker as first line, got:\n%s", out)
	}
	if !strings.Contains(out, `server = "https://registry-1.docker.io"`) {
		t.Errorf("expected well-known server line, got:\n%s", out)
	}
	if strings.Contains(out, "override_path") {
		t.Errorf("expected no override_path for plain hostname mirror, got:\n%s", out)
	}
	if !strings.Contains(out, `[host."https://mirror.corp"]`) {
		t.Errorf("expected host line, got:\n%s", out)
	}
}

func TestGenerateHostsTOML_HarborProxyCache(t *testing.T) {
	out := generateHostsTOML("docker.io", "https://harbor.corp/v2/docker.io")

	if !strings.HasPrefix(out, hostsTomlManagedMarker) {
		t.Errorf("expected managed marker as first line, got:\n%s", out)
	}
	if !strings.Contains(out, `server = "https://registry-1.docker.io"`) {
		t.Errorf("expected well-known server line, got:\n%s", out)
	}
	if !strings.Contains(out, "override_path = true") {
		t.Errorf("expected override_path = true for path-based mirror, got:\n%s", out)
	}
}

func TestGenerateHostsTOML_Default(t *testing.T) {
	out := generateHostsTOML("_default", "https://airgap.internal")

	if !strings.HasPrefix(out, hostsTomlManagedMarker) {
		t.Errorf("expected managed marker as first line, got:\n%s", out)
	}
	if strings.Contains(out, "server =") {
		t.Errorf("expected no server line for _default upstream, got:\n%s", out)
	}
	if !strings.Contains(out, `[host."https://airgap.internal"]`) {
		t.Errorf("expected host line, got:\n%s", out)
	}
}

func TestGenerateHostsTOML_UnknownUpstream(t *testing.T) {
	out := generateHostsTOML("myregistry.corp", "https://mirror.corp")

	if !strings.HasPrefix(out, hostsTomlManagedMarker) {
		t.Errorf("expected managed marker as first line, got:\n%s", out)
	}
	if !strings.Contains(out, `server = "https://myregistry.corp"`) {
		t.Errorf("expected fallback server line for unknown upstream, got:\n%s", out)
	}
}

func TestHasNonRootPath(t *testing.T) {
	cases := []struct {
		url      string
		expected bool
	}{
		{"https://mirror.corp", false},
		{"https://mirror.corp/", false},
		{"https://harbor.corp/v2/docker.io", true},
		{"https://harbor.corp/docker.io", true},
	}

	for _, c := range cases {
		got := hasNonRootPath(c.url)
		if got != c.expected {
			t.Errorf("hasNonRootPath(%q) = %v, want %v", c.url, got, c.expected)
		}
	}
}

func TestIsValidUpstream(t *testing.T) {
	cases := []struct {
		upstream string
		valid    bool
	}{
		{"docker.io", true},
		{"ghcr.io", true},
		{"harbor.corp:5000", true},
		{"_default", true},
		{"myregistry.corp", true},
		{"", false},
		{"/etc/passwd", false},
		{"../etc", false},
		{"..", false},
		{"docker.io/library", false},
		{"foo/bar", false},
	}

	for _, c := range cases {
		got := isValidUpstream(c.upstream)
		if got != c.valid {
			t.Errorf("isValidUpstream(%q) = %v, want %v", c.upstream, got, c.valid)
		}
	}
}

func TestIsManagedByKubesolo_ManagedFile(t *testing.T) {
	f := filepath.Join(t.TempDir(), "hosts.toml")
	content := generateHostsTOML("docker.io", "https://mirror.corp")
	if err := os.WriteFile(f, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}

	managed, err := isManagedByKubesolo(f)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !managed {
		t.Error("expected file generated by kubesolo to be detected as managed")
	}
}

func TestIsManagedByKubesolo_ManualFile(t *testing.T) {
	f := filepath.Join(t.TempDir(), "hosts.toml")
	content := `server = "https://registry-1.docker.io"

[host."https://mirror.corp"]
  capabilities = ["pull", "resolve"]
`
	if err := os.WriteFile(f, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}

	managed, err := isManagedByKubesolo(f)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if managed {
		t.Error("expected manually created file to not be detected as managed")
	}
}

func TestIsManagedByKubesolo_MarkerRemovedByUser(t *testing.T) {
	f := filepath.Join(t.TempDir(), "hosts.toml")
	// Simulate a user who removed the marker line from a previously managed file.
	content := `server = "https://registry-1.docker.io"

[host."https://mirror.corp"]
  capabilities = ["pull", "resolve"]
  ca = ["/etc/ssl/certs/ca.crt"]
`
	if err := os.WriteFile(f, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}

	managed, err := isManagedByKubesolo(f)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if managed {
		t.Error("expected file with marker removed to not be detected as managed")
	}
}

func TestIsManagedByKubesolo_EmptyFile(t *testing.T) {
	f := filepath.Join(t.TempDir(), "hosts.toml")
	if err := os.WriteFile(f, []byte(""), 0644); err != nil {
		t.Fatal(err)
	}

	managed, err := isManagedByKubesolo(f)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if managed {
		t.Error("expected empty file to not be detected as managed")
	}
}
