package containerd

import (
	"bufio"
	"fmt"
	"net/url"
	"os"
	"path/filepath"
	"strings"

	"github.com/portainer/kubesolo/internal/runtime/filesystem"
	"github.com/portainer/kubesolo/types"
	"github.com/rs/zerolog/log"
)

// hostsTomlManagedMarker is written as the first line of every hosts.toml file generated by
// kubesolo. Its presence signals that kubesolo owns the file and will overwrite it on every
// restart. Users who need customisations unsupported by --registry-mirror (custom CA,
// credentials, multiple fallback mirrors) should remove this line; kubesolo will then leave
// the file untouched.
const hostsTomlManagedMarker = "# Managed by kubesolo — overwritten on every restart. Remove this line to manage manually."

// wellKnownUpstreamServers maps registry hostnames to their canonical upstream URLs.
var wellKnownUpstreamServers = map[string]string{
	"docker.io":       "https://registry-1.docker.io",
	"ghcr.io":         "https://ghcr.io",
	"gcr.io":          "https://gcr.io",
	"quay.io":         "https://quay.io",
	"registry.k8s.io": "https://registry.k8s.io",
	"k8s.gcr.io":      "https://k8s.gcr.io",
}

// isValidUpstream reports whether upstream is safe to use as a directory name under
// certs.d. It rejects empty values, path separators, and path traversal sequences that
// could allow writes outside the certs.d directory.
func isValidUpstream(upstream string) bool {
	return upstream != "" && !strings.Contains(upstream, "/") && !strings.Contains(upstream, "..")
}

// hasNonRootPath returns true if the mirror URL contains a non-root path component,
// which indicates that override_path = true is required.
func hasNonRootPath(mirrorURL string) bool {
	u, err := url.Parse(mirrorURL)
	if err != nil {
		return false
	}
	return strings.Trim(u.Path, "/") != ""
}

// isManagedByKubesolo reports whether the file at filePath was generated by kubesolo,
// determined by checking whether its first line matches hostsTomlManagedMarker.
func isManagedByKubesolo(filePath string) (bool, error) {
	f, err := os.Open(filePath)
	if err != nil {
		return false, err
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	if !scanner.Scan() {
		return false, scanner.Err()
	}

	return scanner.Text() == hostsTomlManagedMarker, nil
}

// generateHostsTOML builds the content of a hosts.toml file for the given upstream registry
// and mirror URL. The file always begins with hostsTomlManagedMarker so that kubesolo can
// detect ownership on subsequent startups.
func generateHostsTOML(upstream, mirrorURL string) string {
	var sb strings.Builder

	sb.WriteString(hostsTomlManagedMarker + "\n")

	if upstream != "_default" {
		server, ok := wellKnownUpstreamServers[upstream]
		if !ok {
			server = "https://" + upstream
		}
		sb.WriteString(fmt.Sprintf("server = %q\n", server))
	}

	sb.WriteString("\n")
	sb.WriteString(fmt.Sprintf("[host.%q]\n", mirrorURL))
	sb.WriteString("  capabilities = [\"pull\", \"resolve\"]\n")

	if hasNonRootPath(mirrorURL) {
		sb.WriteString("  override_path = true\n")
	}

	return sb.String()
}

// writeRegistryMirrorFiles writes hosts.toml files for each configured registry mirror
// into the containerd certs.d directory. It is a no-op when mirrors is nil or empty.
// Kubesolo only writes files for registries it is explicitly configured to manage;
// manually created hosts.toml files for other registries are never touched.
func (s *service) writeRegistryMirrorFiles(mirrors map[string]string) error {
	if len(mirrors) == 0 {
		return nil
	}

	if err := filesystem.EnsureDirectoryExists(types.DefaultContainerdCertsDir); err != nil {
		return fmt.Errorf("failed to create certs.d directory: %w", err)
	}

	for upstream, mirrorURL := range mirrors {
		if !isValidUpstream(upstream) {
			log.Warn().Str("component", "containerd").
				Str("upstream", upstream).
				Msg("skipping registry mirror: upstream contains invalid characters")
			continue
		}

		u, err := url.Parse(mirrorURL)
		if err != nil || (u.Scheme != "http" && u.Scheme != "https") || u.Host == "" {
			log.Warn().Str("component", "containerd").
				Str("upstream", upstream).
				Str("mirror", mirrorURL).
				Msg("skipping registry mirror: invalid URL, unsupported scheme (must be http or https), or missing host")
			continue
		}
		if u.User != nil {
			log.Warn().Str("component", "containerd").
				Str("upstream", upstream).
				Msg("skipping registry mirror: credentials in mirror URL are not supported — manage the hosts.toml file manually")
			continue
		}

		dirPath := filepath.Join(types.DefaultContainerdCertsDir, upstream)
		if err := filesystem.EnsureDirectoryExists(dirPath); err != nil {
			return fmt.Errorf("failed to create mirror directory for %s: %w", upstream, err)
		}

		hostsFilePath := filepath.Join(dirPath, "hosts.toml")

		if _, err := os.Stat(hostsFilePath); err == nil {
			managed, err := isManagedByKubesolo(hostsFilePath)
			if err != nil {
				return fmt.Errorf("failed to check hosts.toml ownership for %s: %w", upstream, err)
			}
			if !managed {
				log.Info().Str("component", "containerd").
					Str("upstream", upstream).
					Str("path", hostsFilePath).
					Msg("hosts.toml exists without kubesolo marker — skipping. Delete the file to let kubesolo manage it.")
				continue
			}
		}

		content := generateHostsTOML(upstream, mirrorURL)
		if err := os.WriteFile(hostsFilePath, []byte(content), 0644); err != nil {
			return fmt.Errorf("failed to write hosts.toml for %s: %w", upstream, err)
		}

		log.Info().Str("component", "containerd").
			Str("upstream", upstream).
			Str("mirror", u.Redacted()).
			Msg("wrote registry mirror hosts.toml")
	}

	return nil
}
