package network

import (
	"bufio"
	"fmt"
	"net"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/rs/zerolog/log"
)

// maxNameservers is the Linux resolv.conf hard limit (MAXNS in libc/kubelet).
const maxNameservers = 3

var (
	rfc1123 = `^[a-zA-Z0-9]([a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])?(\.[a-zA-Z0-9]([a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])?)*$`
)

// GetLocalIPs returns all non-loopback IPv4 addresses
func GetLocalIPs() ([]net.IP, error) {
	addrs, err := net.InterfaceAddrs()
	if err != nil {
		return nil, err
	}

	ips := []net.IP{}
	for _, addr := range addrs {
		if ipnet, ok := addr.(*net.IPNet); ok && !ipnet.IP.IsLoopback() {
			if ipnet.IP.To4() != nil {
				ips = append(ips, ipnet.IP)
			}
		}
	}
	return append(ips, net.ParseIP("127.0.0.1")), nil
}

// GetNodeIP returns the first non-loopback IP address of the node
func GetNodeIP() (string, error) {
	addrs, err := net.InterfaceAddrs()
	if err != nil {
		return "127.0.0.1", fmt.Errorf("failed to get node IP address: %v", err)
	}

	for _, addr := range addrs {
		if ipnet, ok := addr.(*net.IPNet); ok && !ipnet.IP.IsLoopback() && ipnet.IP.To4() != nil {
			return ipnet.IP.To4().String(), nil
		}
	}

	return "127.0.0.1", fmt.Errorf("could not find non-loopback private IP address")
}

// IsIPv4Address returns true if the given string is a valid IPv4 address
func IsIPv4Address(ip string) bool {
	return net.ParseIP(ip) != nil && net.ParseIP(ip).To4() != nil
}

// IsDNSName returns true if the given string is a valid DNS name
// it follows the RFC 1123 specification for DNS names
func IsDNSName(name string) bool {
	if name == "" || len(name) > 253 {
		return false
	}

	// RFC 1123 compliant DNS name pattern
	matched, _ := regexp.MatchString(rfc1123, name)
	return matched
}

// instanceMetadataServiceIP is the IP used by cloud providers (AWS, GCP, Azure)
// for instance metadata services. This must be allowed as a valid nameserver
// even though it is a link-local address.
var instanceMetadataServiceIP = net.ParseIP("169.254.169.254")

// GetHostResolvConf returns the path to a resolv.conf file that contains
// real upstream nameservers suitable for use by pods. It checks common resolv.conf
// locations and validates that they contain usable nameservers (global unicast).
// If no valid resolv.conf is found, it generates a fallback with public DNS servers.
// This follows the same approach as k3s locateOrGenerateResolvConf.
func GetHostResolvConf(dataDir string) string {
	resolvConfs := []string{"/etc/resolv.conf", "/run/systemd/resolve/resolv.conf"}
	for _, conf := range resolvConfs {
		if isValidResolvConf(conf) {
			if conf != "/etc/resolv.conf" {
				log.Info().Str("component", "network").
					Msgf("/etc/resolv.conf has unusable nameservers, using %s", conf)
			}
			// Sanitize if nameserver count exceeds the Linux hard limit of 3.
			sanitized, err := sanitizeResolvConf(conf, dataDir)
			if err != nil {
				log.Warn().Str("component", "network").Err(err).
					Msg("failed to sanitize resolv.conf, using original")
				return conf
			}
			return sanitized
		}
	}

	// No valid resolv.conf found — generate a fallback
	resolvConf := filepath.Join(dataDir, "resolv.conf")
	if err := os.WriteFile(resolvConf, []byte("nameserver 8.8.8.8\nnameserver 1.1.1.1\n"), 0644); err != nil {
		log.Error().Str("component", "network").Msgf("failed to write fallback resolv.conf: %v", err)
		return "/etc/resolv.conf"
	}
	log.Warn().Str("component", "network").
		Msg("host resolv.conf includes loopback or link-local nameservers - using autogenerated resolv.conf with 8.8.8.8 and 1.1.1.1")
	return resolvConf
}

// sanitizeResolvConf reads the resolv.conf at srcPath, deduplicates nameservers,
// and caps them to maxNameservers. If no sanitization is needed, srcPath is returned
// unchanged. Otherwise a sanitized copy is written to dataDir/resolv.conf.
func sanitizeResolvConf(srcPath, dataDir string) (string, error) {
	file, err := os.Open(srcPath)
	if err != nil {
		return srcPath, nil
	}
	defer file.Close()

	nameserverRe := regexp.MustCompile(`^nameserver\s+([^\s]*)`)

	var otherLines []string
	var nameservers []string
	seen := make(map[string]bool)

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := scanner.Text()
		match := nameserverRe.FindStringSubmatch(line)
		if len(match) == 2 {
			ns := match[1]
			if !seen[ns] {
				seen[ns] = true
				nameservers = append(nameservers, ns)
			}
			// duplicate/excess nameserver lines are dropped
			continue
		}
		otherLines = append(otherLines, line)
	}
	if err := scanner.Err(); err != nil {
		return srcPath, fmt.Errorf("scanning resolv.conf: %w", err)
	}

	if len(nameservers) <= maxNameservers {
		return srcPath, nil
	}

	omitted := nameservers[maxNameservers:]
	nameservers = nameservers[:maxNameservers]
	log.Warn().Str("component", "network").
		Strs("omitted_nameservers", omitted).
		Msgf("host resolv.conf has more than %d nameservers; capping to prevent kubelet warnings", maxNameservers)

	var b strings.Builder
	for _, ns := range nameservers {
		b.WriteString("nameserver ")
		b.WriteString(ns)
		b.WriteString("\n")
	}
	for _, line := range otherLines {
		b.WriteString(line)
		b.WriteString("\n")
	}

	destPath := filepath.Join(dataDir, "resolv.conf")
	if err := os.WriteFile(destPath, []byte(b.String()), 0644); err != nil {
		return srcPath, fmt.Errorf("writing sanitized resolv.conf: %w", err)
	}
	return destPath, nil
}

// isValidResolvConf checks whether a resolv.conf file exists and contains
// at least one valid upstream nameserver (global unicast address).
func isValidResolvConf(path string) bool {
	file, err := os.Open(path)
	if err != nil {
		return false
	}
	defer file.Close()

	nameserver := regexp.MustCompile(`^nameserver\s+([^\s]*)`)
	scanner := bufio.NewScanner(file)
	foundNameserver := false
	for scanner.Scan() {
		ipMatch := nameserver.FindStringSubmatch(scanner.Text())
		if len(ipMatch) == 2 {
			if !isValidNameserver(ipMatch[1]) {
				return false
			}
			foundNameserver = true
		}
	}
	if err := scanner.Err(); err != nil {
		return false
	}
	return foundNameserver
}

// isValidNameserver returns true if the IP is a valid upstream resolver address.
// Resolver IPs must be global unicast, with the exception of the cloud instance
// metadata service IP (169.254.169.254), which some cloud providers require
// for private DNS to work properly.
func isValidNameserver(addr string) bool {
	ip := net.ParseIP(addr)
	if ip == nil {
		return false
	}
	if !ip.IsGlobalUnicast() && !ip.Equal(instanceMetadataServiceIP) {
		return false
	}
	return true
}
