name: CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm64, arm, riscv64]
    steps:
      - name: "checkout the current branch"
        uses: actions/checkout@v4
      - name: "set up golang"
        uses: actions/setup-go@v5.0.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - name: "Install cross-compilation toolchains"
        run: sudo make install-cross-compilers
      - name: "Build the binary for ${{ matrix.goos }}/${{ matrix.goarch }}"
        run: make build GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }}
      - uses: actions/upload-artifact@v4
        with:
          name: kubesolo-${{ matrix.goos }}-${{ matrix.goarch }}
          path: ./dist/kubesolo
          retention-days: 30